%dev.quarkus.dev-ui.cors.enabled=false

%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=
%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:./data/manufacturingdb;AUTO_SERVER=TRUE
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true

quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:3000,https://3000-firebase-manufacturing-plan-1771902931191.cluster-f73ibkkuije66wssuontdtbx6q.cloudworkstations.dev