# Habilitar CORS
quarkus.http.cors=true

# Permitir origem do Firebase / Cloud Workstations
quarkus.http.cors.origins=*

# Métodos permitidos
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Headers permitidos
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Permitir credenciais (se precisar)
# quarkus.http.cors.access-control-allow-credentials=true